services:
  app:
    restart: unless-stopped
    image: ghcr.io/lzc256/firefly-iii-alpine:latest
    volumes:
      - .env:/var/www/html/.env
      - ./sqlite3.db:/var/www/html/sqlite3.db
      - ./upload:/var/www/html/storage/upload
    ports:
      - 127.0.0.1:8080:8080

  cron:
    image: alpine
    restart: unless-stopped
    env_file: .env
    stop_grace_period: 0s
    command: |
      sh -c "
      apk add tzdata &&
      (ln -s /usr/share/zoneinfo/$$TZ /etc/localtime || true) &&
      echo '*/20 * * * * wget -qO- http://app:8080/api/v1/cron/$STATIC_CRON_TOKEN > /dev/null; date' | crontab - &&
      exec crond -f -L /dev/stdout"
    depends_on:
      - app
